#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="$POSTGRES_DB"<<-EOSQL
   CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

   CREATE TABLE IF NOT EXISTS countries (
      country_code CHAR(2) PRIMARY KEY,
      country_name VARCHAR(100) NOT NULL,
      continent VARCHAR(50),
      currency_code VARCHAR(6)
   );

   INSERT INTO countries (country_code, country_name, continent, currency_code) VALUES
      ('AF', 'Afghanistan', 'Asia', 'AFN'),
      ('AL', 'Albania', 'Europe', 'ALL'),
      ('DZ', 'Algeria', 'Africa', 'DZD'),
      ('AS', 'American Samoa', 'Oceania', 'USD'),
      ('AD', 'Andorra', 'Europe', 'EUR'),
      ('AO', 'Angola', 'Africa', 'AOA'),
      ('AI', 'Anguilla', 'North America', 'XCD'),
      ('AQ', 'Antarctica', 'Antarctica', ''),
      ('AG', 'Antigua and Barbuda', 'North America', 'XCD'),
      ('AR', 'Argentina', 'South America', 'ARS'),
      ('AM', 'Armenia', 'Asia', 'AMD'),
      ('AW', 'Aruba', 'North America', 'AWG'),
      ('AU', 'Australia', 'Oceania', 'AUD'),
      ('AT', 'Austria', 'Europe', 'EUR'),
      ('AZ', 'Azerbaijan', 'Asia', 'AZN'),
      ('BS', 'Bahamas', 'North America', 'BSD'),
      ('BH', 'Bahrain', 'Asia', 'BHD'),
      ('BD', 'Bangladesh', 'Asia', 'BDT'),
      ('BB', 'Barbados', 'North America', 'BBD'),
      ('BY', 'Belarus', 'Europe', 'BYN'),
      ('BE', 'Belgium', 'Europe', 'EUR'),
      ('BZ', 'Belize', 'North America', 'BZD'),
      ('BJ', 'Benin', 'Africa', 'XOF'),
      ('BM', 'Bermuda', 'North America', 'BMD'),
      ('BT', 'Bhutan', 'Asia', 'BTN'),
      ('BO', 'Bolivia', 'South America', 'BOB'),
      ('BA', 'Bosnia and Herzegovina', 'Europe', 'BAM'),
      ('BW', 'Botswana', 'Africa', 'BWP'),
      ('BR', 'Brazil', 'South America', 'BRL'),
      ('IO', 'British Indian Ocean Territory', 'Africa', 'USD'),
      ('VG', 'British Virgin Islands', 'North America', 'USD'),
      ('BN', 'Brunei Darussalam', 'Asia', 'BND'),
      ('BG', 'Bulgaria', 'Europe', 'BGN'),
      ('BF', 'Burkina Faso', 'Africa', 'XOF'),
      ('BI', 'Burundi', 'Africa', 'BIF'),
      ('CV', 'Cabo Verde', 'Africa', 'CVE'),
      ('KH', 'Cambodia', 'Asia', 'KHR'),
      ('CM', 'Cameroon', 'Africa', 'XAF'),
      ('CA', 'Canada', 'North America', 'CAD'),
      ('KY', 'Cayman Islands', 'North America', 'KYD'),
      ('CF', 'Central African Republic', 'Africa', 'XAF'),
      ('TD', 'Chad', 'Africa', 'XAF'),
      ('CL', 'Chile', 'South America', 'CLP'),
      ('CN', 'China', 'Asia', 'CNY'),
      ('CX', 'Christmas Island', 'Asia', 'AUD'),
      ('CC', 'Cocos (Keeling) Islands', 'Asia', 'AUD'),
      ('CO', 'Colombia', 'South America', 'COP'),
      ('KM', 'Comoros', 'Africa', 'KMF'),
      ('CD', 'Congo, Democratic Republic of the', 'Africa', 'CDF'),
      ('CG', 'Congo, Republic of the', 'Africa', 'XAF'),
      ('CK', 'Cook Islands', 'Oceania', 'NZD'),
      ('CR', 'Costa Rica', 'North America', 'CRC'),
      ('CI', 'Côte d''Ivoire', 'Africa', 'XOF'),
      ('HR', 'Croatia', 'Europe', 'EUR'),
      ('CU', 'Cuba', 'North America', 'CUP'),
      ('CW', 'Curaçao', 'North America', 'ANG'),
      ('CY', 'Cyprus', 'Asia', 'EUR'),
      ('CZ', 'Czech Republic', 'Europe', 'CZK'),
      ('DK', 'Denmark', 'Europe', 'DKK'),
      ('DJ', 'Djibouti', 'Africa', 'DJF'),
      ('DM', 'Dominica', 'North America', 'XCD'),
      ('DO', 'Dominican Republic', 'North America', 'DOP'),
      ('EC', 'Ecuador', 'South America', 'USD'),
      ('EG', 'Egypt', 'Africa', 'EGP'),
      ('SV', 'El Salvador', 'North America', 'USD'),
      ('GQ', 'Equatorial Guinea', 'Africa', 'XAF'),
      ('ER', 'Eritrea', 'Africa', 'ERN'),
      ('EE', 'Estonia', 'Europe', 'EUR'),
      ('SZ', 'Eswatini', 'Africa', 'SZL'),
      ('ET', 'Ethiopia', 'Africa', 'ETB'),
      ('FK', 'Falkland Islands', 'South America', 'FKP'),
      ('FO', 'Faroe Islands', 'Europe', 'DKK'),
      ('FJ', 'Fiji', 'Oceania', 'FJD'),
      ('FI', 'Finland', 'Europe', 'EUR'),
      ('FR', 'France', 'Europe', 'EUR'),
      ('GF', 'French Guiana', 'South America', 'EUR'),
      ('PF', 'French Polynesia', 'Oceania', 'XPF'),
      ('GA', 'Gabon', 'Africa', 'XAF'),
      ('GM', 'Gambia', 'Africa', 'GMD'),
      ('GE', 'Georgia', 'Asia', 'GEL'),
      ('DE', 'Germany', 'Europe', 'EUR'),
      ('GH', 'Ghana', 'Africa', 'GHS'),
      ('GI', 'Gibraltar', 'Europe', 'GIP'),
      ('GR', 'Greece', 'Europe', 'EUR'),
      ('GL', 'Greenland', 'North America', 'DKK'),
      ('GD', 'Grenada', 'North America', 'XCD'),
      ('GP', 'Guadeloupe', 'North America', 'EUR'),
      ('GU', 'Guam', 'Oceania', 'USD'),
      ('GT', 'Guatemala', 'North America', 'GTQ'),
      ('GG', 'Guernsey', 'Europe', 'GBP'),
      ('GN', 'Guinea', 'Africa', 'GNF'),
      ('GW', 'Guinea-Bissau', 'Africa', 'XOF'),
      ('GY', 'Guyana', 'South America', 'GYD'),
      ('HT', 'Haiti', 'North America', 'HTG'),
      ('HM', 'Heard Island and McDonald Islands', 'Antarctica', 'AUD'),
      ('VA', 'Holy See', 'Europe', 'EUR'),
      ('HN', 'Honduras', 'North America', 'HNL'),
      ('HK', 'Hong Kong', 'Asia', 'HKD'),
      ('HU', 'Hungary', 'Europe', 'HUF'),
      ('IS', 'Iceland', 'Europe', 'ISK'),
      ('IN', 'India', 'Asia', 'INR'),
      ('ID', 'Indonesia', 'Asia', 'IDR'),
      ('IR', 'Iran', 'Asia', 'IRR'),
      ('IQ', 'Iraq', 'Asia', 'IQD'),
      ('IE', 'Ireland', 'Europe', 'EUR'),
      ('IM', 'Isle of Man', 'Europe', 'GBP'),
      ('IL', 'Israel', 'Asia', 'ILS'),
      ('IT', 'Italy', 'Europe', 'EUR'),
      ('JM', 'Jamaica', 'North America', 'JMD'),
      ('JP', 'Japan', 'Asia', 'JPY'),
      ('JE', 'Jersey', 'Europe', 'GBP'),
      ('JO', 'Jordan', 'Asia', 'JOD'),
      ('KZ', 'Kazakhstan', 'Asia', 'KZT'),
      ('KE', 'Kenya', 'Africa', 'KES'),
      ('KI', 'Kiribati', 'Oceania', 'AUD'),
      ('KP', 'Korea, Democratic People''s Republic of', 'Asia', 'KPW'),
      ('KR', 'Korea, Republic of', 'Asia', 'KRW'),
      ('KW', 'Kuwait', 'Asia', 'KWD'),
      ('KG', 'Kyrgyzstan', 'Asia', 'KGS'),
      ('LA', 'Lao People''s Democratic Republic', 'Asia', 'LAK'),
      ('LV', 'Latvia', 'Europe', 'EUR'),
      ('LB', 'Lebanon', 'Asia', 'LBP'),
      ('LS', 'Lesotho', 'Africa', 'LSL'),
      ('LR', 'Liberia', 'Africa', 'LRD'),
      ('LY', 'Libya', 'Africa', 'LYD'),
      ('LI', 'Liechtenstein', 'Europe', 'CHF'),
      ('LT', 'Lithuania', 'Europe', 'EUR'),
      ('LU', 'Luxembourg', 'Europe', 'EUR'),
      ('MO', 'Macao', 'Asia', 'MOP'),
      ('MG', 'Madagascar', 'Africa', 'MGA'),
      ('MW', 'Malawi', 'Africa', 'MWK'),
      ('MY', 'Malaysia', 'Asia', 'MYR'),
      ('MV', 'Maldives', 'Asia', 'MVR'),
      ('ML', 'Mali', 'Africa', 'XOF'),
      ('MT', 'Malta', 'Europe', 'EUR'),
      ('MH', 'Marshall Islands', 'Oceania', 'USD'),
      ('MQ', 'Martinique', 'North America', 'EUR'),
      ('MR', 'Mauritania', 'Africa', 'MRU'),
      ('MU', 'Mauritius', 'Africa', 'MUR'),
      ('YT', 'Mayotte', 'Africa', 'EUR'),
      ('MX', 'Mexico', 'North America', 'MXN'),
      ('FM', 'Micronesia (Federated States of)', 'Oceania', 'USD'),
      ('MD', 'Moldova', 'Europe', 'MDL'),
      ('MC', 'Monaco', 'Europe', 'EUR'),
      ('MN', 'Mongolia', 'Asia', 'MNT'),
      ('ME', 'Montenegro', 'Europe', 'EUR'),
      ('MS', 'Montserrat', 'North America', 'XCD'),
      ('MA', 'Morocco', 'Africa', 'MAD'),
      ('MZ', 'Mozambique', 'Africa', 'MZN'),
      ('MM', 'Myanmar', 'Asia', 'MMK'),
      ('NA', 'Namibia', 'Africa', 'NAD'),
      ('NR', 'Nauru', 'Oceania', 'AUD'),
      ('NP', 'Nepal', 'Asia', 'NPR'),
      ('NL', 'Netherlands', 'Europe', 'EUR'),
      ('NC', 'New Caledonia', 'Oceania', 'XPF'),
      ('NZ', 'New Zealand', 'Oceania', 'NZD'),
      ('NI', 'Nicaragua', 'North America', 'NIO'),
      ('NE', 'Niger', 'Africa', 'XOF'),
      ('NG', 'Nigeria', 'Africa', 'NGN'),
      ('NU', 'Niue', 'Oceania', 'NZD'),
      ('NF', 'Norfolk Island', 'Oceania', 'AUD'),
      ('MP', 'Northern Mariana Islands', 'Oceania', 'USD'),
      ('NO', 'Norway', 'Europe', 'NOK'),
      ('OM', 'Oman', 'Asia', 'OMR'),
      ('PK', 'Pakistan', 'Asia', 'PKR'),
      ('PW', 'Palau', 'Oceania', 'USD'),
      ('PS', 'Palestine, State of', 'Asia', 'ILS'),
      ('PA', 'Panama', 'North America', 'PAB'),
      ('PG', 'Papua New Guinea', 'Oceania', 'PGK'),
      ('PY', 'Paraguay', 'South America', 'PYG'),
      ('PE', 'Peru', 'South America', 'PEN'),
      ('PH', 'Philippines', 'Asia', 'PHP'),
      ('PN', 'Pitcairn', 'Oceania', 'NZD'),
      ('PL', 'Poland', 'Europe', 'PLN'),
      ('PT', 'Portugal', 'Europe', 'EUR'),
      ('PR', 'Puerto Rico', 'North America', 'USD'),
      ('QA', 'Qatar', 'Asia', 'QAR'),
      ('MK', 'Republic of North Macedonia', 'Europe', 'MKD'),
      ('RO', 'Romania', 'Europe', 'RON'),
      ('RU', 'Russian Federation', 'Europe', 'RUB'),
      ('RW', 'Rwanda', 'Africa', 'RWF'),
      ('RE', 'Réunion', 'Africa', 'EUR'),
      ('BL', 'Saint Barthélemy', 'North America', 'EUR'),
      ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Africa', 'SHP'),
      ('KN', 'Saint Kitts and Nevis', 'North America', 'XCD'),
      ('LC', 'Saint Lucia', 'North America', 'XCD'),
      ('MF', 'Saint Martin (French part)', 'North America', 'EUR'),
      ('PM', 'Saint Pierre and Miquelon', 'North America', 'EUR'),
      ('VC', 'Saint Vincent and the Grenadines', 'North America', 'XCD'),
      ('WS', 'Samoa', 'Oceania', 'WST'),
      ('SM', 'San Marino', 'Europe', 'EUR'),
      ('ST', 'Sao Tome and Principe', 'Africa', 'STN'),
      ('SA', 'Saudi Arabia', 'Asia', 'SAR'),
      ('SN', 'Senegal', 'Africa', 'XOF'),
      ('RS', 'Serbia', 'Europe', 'RSD'),
      ('SC', 'Seychelles', 'Africa', 'SCR'),
      ('SL', 'Sierra Leone', 'Africa', 'SLL'),
      ('SG', 'Singapore', 'Asia', 'SGD'),
      ('SX', 'Sint Maarten (Dutch part)', 'North America', 'ANG'),
      ('SK', 'Slovakia', 'Europe', 'EUR'),
      ('SI', 'Slovenia', 'Europe', 'EUR'),
      ('SB', 'Solomon Islands', 'Oceania', 'SBD'),
      ('SO', 'Somalia', 'Africa', 'SOS'),
      ('ZA', 'South Africa', 'Africa', 'ZAR'),
      ('GS', 'South Georgia and the South Sandwich Islands', 'Antarctica', 'GBP'),
      ('SS', 'South Sudan', 'Africa', 'SSP'),
      ('ES', 'Spain', 'Europe', 'EUR'),
      ('LK', 'Sri Lanka', 'Asia', 'LKR'),
      ('SD', 'Sudan', 'Africa', 'SDG'),
      ('SR', 'Suriname', 'South America', 'SRD'),
      ('SJ', 'Svalbard and Jan Mayen', 'Europe', 'NOK'),
      ('SE', 'Sweden', 'Europe', 'SEK'),
      ('CH', 'Switzerland', 'Europe', 'CHF'),
      ('SY', 'Syrian Arab Republic', 'Asia', 'SYP'),
      ('TW', 'Taiwan', 'Asia', 'TWD'),
      ('TJ', 'Tajikistan', 'Asia', 'TJS'),
      ('TZ', 'Tanzania', 'Africa', 'TZS'),
      ('TH', 'Thailand', 'Asia', 'THB'),
      ('TL', 'Timor-Leste', 'Asia', 'USD'),
      ('TG', 'Togo', 'Africa', 'XOF'),
      ('TK', 'Tokelau', 'Oceania', 'NZD'),
      ('TO', 'Tonga', 'Oceania', 'TOP'),
      ('TT', 'Trinidad and Tobago', 'North America', 'TTD'),
      ('TN', 'Tunisia', 'Africa', 'TND'),
      ('TR', 'Turkey', 'Asia', 'TRY'),
      ('TM', 'Turkmenistan', 'Asia', 'TMT'),
      ('TC', 'Turks and Caicos Islands', 'North America', 'USD'),
      ('TV', 'Tuvalu', 'Oceania', 'AUD'),
      ('UG', 'Uganda', 'Africa', 'UGX'),
      ('UA', 'Ukraine', 'Europe', 'UAH'),
      ('AE', 'United Arab Emirates', 'Asia', 'AED'),
      ('GB', 'United Kingdom', 'Europe', 'GBP'),
      ('US', 'United States', 'North America', 'USD'),
      ('UM', 'United States Minor Outlying Islands', 'Oceania', 'USD'),
      ('UY', 'Uruguay', 'South America', 'UYU'),
      ('UZ', 'Uzbekistan', 'Asia', 'UZS'),
      ('VU', 'Vanuatu', 'Oceania', 'VUV'),
      ('VE', 'Venezuela', 'South America', 'VES'),
      ('VN', 'Viet Nam', 'Asia', 'VND'),
      ('VI', 'Virgin Islands (U.S.)', 'North America', 'USD'),
      ('WF', 'Wallis and Futuna', 'Oceania', 'XPF'),
      ('EH', 'Western Sahara', 'Africa', 'MAD'),
      ('YE', 'Yemen', 'Asia', 'YER'),
      ('ZM', 'Zambia', 'Africa', 'ZMW'),
      ('ZW', 'Zimbabwe', 'Africa', 'ZWL')
   ON CONFLICT (country_code) DO NOTHING;


   CREATE DATABASE oauth2;
   GRANT ALL PRIVILEGES ON DATABASE oauth2 TO postgres;

   CREATE DATABASE grafana;
   GRANT ALL PRIVILEGES ON DATABASE grafana TO postgres;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="oauth2"<<-EOSQL
   CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="grafana"<<-EOSQL
   CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL